version: '3'
services:
  server-side-rendering-server:
    build:
      context: .
      dockerfile: Dockerfile-node.dockerfile
    volumes:
      - /app/node_modules
      - ./:/app/
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=server-side-rendering-redis
    ports:
      - 3000:3000
  server-side-rendering-redis:
    image: redis:alpine
    ports:
      - 6379:6379