version: '3'
services:
  queue-master:
    build:
      context: .
      dockerfile: Dockerfile-node.dockerfile
    volumes:
      - /app/node_modules
      - ./:/app/
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=queue-worker-redis
    command: ["npm", "run", "start:master"]
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile-node.dockerfile
    volumes:
      - ./:/app/
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=queue-worker-redis
      - PROCESS_NAME=queue-worker
    command: ["npm", "run", "start:worker"]
  queue-worker-2:
    build:
      context: .
      dockerfile: Dockerfile-node.dockerfile
    volumes:
      - ./:/app/
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=queue-worker-redis
      - PROCESS_NAME=queue-worker-2
    command: ["npm", "run", "start:worker"]
  queue-worker-redis:
    image: redis:alpine